### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by kli017** [dangvu5998/Document-image-quality-assessment#1]
hello@dangvu5998 may I know what dataset were used in this project?

**Comment by reyhanegh** [comment]
> hello@dangvu5998 may I know what dataset were used in this project?

hi @kli017 
I think [DIQA: Document Image Quality Assessment Datasets](https://lampsrv02.umiacs.umd.edu/projdb/project.php?id=73) were used.
which also be used in [DIQA_CNN](https://github.com/rjchern/DIQA_CNN)
but it is inapproachable  for me and I've could not access to it yet.
